name: publish

inputs:
  client_onvpn: 
     description: "github token of project"
     required: true
  server_host:
    description: "host of server"
    required: true
  server_username:
    description: "username for server"
    required: true
  ssh_private_key:
    description: "private key for server"
    required: true

runs:
  using: 'composite'
  steps:
  - name: Install OpenVPN
    shell: bash
    run: |
      sudo apt update
      sudo apt install -y openvpn openvpn-systemd-resolved
      echo "${{ inputs.client_onvpn }}" > client.ovpn

  - name: Connect to VPN
    uses: "kota65535/github-openvpn-connect-action@v2"
    with:
      config_file: ./client.ovpn

  - name: Use SSH
    uses: appleboy/ssh-action@master
    with: 
      host: ${{ inputs.server_host }}
      username: ${{ inputs.server_username }}
      key: ${{ inputs.ssh_private_key }}
      script: |
        ls
        cd etc/glasscore
        ./deploy.sh