name: publish

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: app
        path: dist

    - name: Push docker image
      shell: bash
      run: |
        docker login ghcr.io
        docker build . --tag ghcr.io/mrcplatform/${{ github.event.repository.name }}:latest
        docker push ghcr.io/mrcplatform/${{ github.event.repository.name }}:latest