name: publish

inputs:
  repository_token: 
     description: "github token of project"
     required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: app
        path: dist

    - name: Push docker image
      shell: bash
      run: |
        echo "${{ inputs.repository_token }}" | docker login ghcr.io -u mrcplatform --password-stdin
        docker build . --file Dockerfile --tag ghcr.io/mrcplatform/${{ github.event.repository.name }}:latest
        docker push ghcr.io/mrcplatform/${{ github.event.repository.name }}:latest

