name: publish

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: app
        path: dist

    - name: Push docker image
      shell: bash
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" > ~/ghcr_token
        docker build . --tag ghcr.io/mrcplatform/${{ github.event.repository.name }}:latest
        rm ~/ghcr_token
        docker run ghcr.io/mrcplatform/${{ github.event.repository.name }}:latest
        docker push ghcr.io/mrcplatform/${{ github.event.repository.name }}:latest