name: pull-request
description: "action for pull request in projects in golang"
runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.3
    - name: install, build and test
      shell: bash
      run: |
          go get ./...  
          go build -v ./...
          go test -v ./...
